# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Everyday ANN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: evann-test-pip-${{ hashFiles('**/requirements_NOCUDA.txt') }}
        restore-keys: |
          evann-test-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements_NOCUDA.txt ]; then pip install -r requirements_NOCUDA.txt; fi
    - name: Test with pytest
      run: |
        pytest -W ignore::UserWarning
