name: Everyday ANN

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: evann-test-pip-${{ hashFiles('**/requirements_NOCUDA.txt') }}
        restore-keys: |
          evann-test-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn
        if [ -f requirements_NOCUDA.txt ]; then pip install -r requirements_NOCUDA.txt; fi
    - name: Start FastAPI server
      run: |
        uvicorn app:app --host 0.0.0.0 --port 8000 &
        echo $! > uvicorn.pid
    - name: Wait for server to start
      run: sleep 10
    - name: Run tests with return file
      run: |
        # Train the model and get the model file
        curl -s -F "data_file=@Crop_Recommendation.csv" -F "trial_details={\"num_epochs\":{\"high\":400}}" -F "n_trials=1" http://127.0.0.1:8000/train?return_file=true --output docker_test_model.pkl
        echo "Model file saved as docker_test_model.pkl"
        sleep 5
        # Predict with the saved model file and Testing_Sample.csv
        PREDICT_RESPONSE=$(curl -s -X POST "http://127.0.0.1:8000/predict" \
          -F "model_file=@docker_test_model.pkl" \
          -F "data_file=@Crop_Recommendation.csv" \
          -F "input_data={\"Nitrogen\": [90], \"Phosphorus\": [42], \"Potassium\": [43], \"Temperature\": [20.87974371], \"Humidity\": [82.00274423], \"pH_Value\": [6.502985292], \"Rainfall\": [202.9355362], \"Crop\": [\"-\"]}")
        echo "Predict Response with saved model: $PREDICT_RESPONSE"

        # Check if predictions are present in the response
        echo $PREDICT_RESPONSE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
    - name: Run tests with no return file
      run: |
        # Train the model with uploaded data file and get model ID
        TRAIN_RESPONSE=$(curl -s -F "data_file=@Crop_Recommendation.csv" -F "trial_details={\"num_epochs\":{\"high\":400}}" -F "n_trials=1" http://127.0.0.1:8000/train)
        echo "Train Response: $TRAIN_RESPONSE"

        # Extract user_model_file from the response
        MODEL_ID=$(echo $TRAIN_RESPONSE | python3 -c "import sys, json; print(json.load(sys.stdin)['user_model_file'])")
        echo "Model ID: $MODEL_ID"
        sleep 5
        # Predict with uploaded model ID, data file, and JSON data
        PREDICT_RESPONSE=$(curl -s -X POST "http://127.0.0.1:8000/predict" \
          -F "data_file=@Crop_Recommendation.csv" \
          -F "input_data={\"Nitrogen\": [90], \"Phosphorus\": [42], \"Potassium\": [43], \"Temperature\": [20.87974371], \"Humidity\": [82.00274423], \"pH_Value\": [6.502985292], \"Rainfall\": [202.9355362], \"Crop\": [\"-\"]}" \
          -F "user_model_file=$MODEL_ID")
        echo "Predict Response: $PREDICT_RESPONSE"

        # Check if predictions are present in the response
        echo $PREDICT_RESPONSE | grep -q '"predictions"' || (echo "Predictions not found in response" && exit 1)
    - name: Stop FastAPI server
      run: |
        kill $(cat uvicorn.pid)
